import { ArrowLeft, FileText } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export default function TermsPage() {
  const navigate = useNavigate();
  return (
    <div className="pb-28 px-4 pt-6 max-w-lg mx-auto">
      <div className="flex items-center gap-3 mb-6">
        <button onClick={() => navigate(-1)} className="w-9 h-9 rounded-xl bg-secondary flex items-center justify-center">
          <ArrowLeft className="w-5 h-5" />
        </button>
        <h1 className="text-xl font-bold">Terms of Service</h1>
      </div>

      <div className="bg-card rounded-2xl p-5 card-shadow mb-4">
        <FileText className="w-8 h-8 text-primary mb-2" />
        <h2 className="text-base font-bold mb-1">Terms of Use</h2>
        <p className="text-xs text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
      </div>

      <article className="prose prose-sm max-w-none [&_h2]:text-sm [&_h2]:font-bold [&_h2]:mt-5 [&_h2]:mb-2 [&_p]:text-xs [&_p]:text-muted-foreground [&_p]:leading-relaxed [&_li]:text-xs space-y-3 bg-card rounded-2xl p-5 card-shadow">
        <h2>1. Acceptance</h2>
        <p>By using Finance Friend, you agree to these terms. If you don't agree, please uninstall the app.</p>

        <h2>2. License</h2>
        <p>You get a personal, non-exclusive, non-transferable license to use the app for tracking your own personal finances.</p>

        <h2>3. Not financial advice</h2>
        <p>All insights, AI suggestions, anomaly alerts, and forecasts are <b>informational only</b>. Finance Friend is not a financial advisor. Make financial decisions at your own discretion.</p>

        <h2>4. AI-generated content</h2>
        <p>AI responses are generated by third-party language models and may contain errors. Verify important information independently.</p>

        <h2>5. Data responsibility</h2>
        <p>Your data is stored locally. You are responsible for backing it up via the Export feature. Uninstalling the app or clearing app data will permanently delete your records.</p>

        <h2>6. Ads</h2>
        <p>The app may display ads. Ad content is managed by AdMob and we do not endorse any advertised products.</p>

        <h2>7. No warranty</h2>
        <p>The app is provided "as is" without any warranty. We are not liable for any losses arising from use of the app.</p>

        <h2>8. Changes</h2>
        <p>We may update these terms; continued use after changes means acceptance.</p>
      </article>
    </div>
  );
}
